In [7]:
import numpy as np



1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [10]:
vector = np.array([i for i in range(1, 11)])

print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
mtx = np.zeros((3, 3), dtype=int)

print(mtx)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [9]:
mtx = np.random.randint(1, 10 , (5 , 5))

print(mtx)

[[8 4 6 1 5]
 [3 5 6 4 4]
 [7 9 4 7 2]
 [3 9 7 5 6]
 [4 2 2 9 6]]


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
mtx = np.random.rand(4, 4)

print(mtx)

[[0.65463178 0.08033825 0.12460911 0.67890803]
 [0.58531938 0.48774071 0.71304493 0.3834277 ]
 [0.60336944 0.92864385 0.56972056 0.43110292]
 [0.2467185  0.06716777 0.64487004 0.34632342]]


5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 10, (5))
b = np.random.randint(1, 10, (5))

print(f'a: {a}')
print(f'b: {b}')
print()
print(f'a + b = {a + b}')
print(f'a - b = {a - b}')
print(f'a * b = {a * b}')

a: [1 4 1 3 1]
b: [2 7 2 7 9]

a + b = [ 3 11  3 10 10]
a - b = [-1 -3 -1 -4 -8]
a * b = [ 2 28  2 21  9]


6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 10, (5))
b = np.random.randint(1, 10, (5))

print(f'a: {a}')
print(f'b: {b}')
print()
print(f'скалярний добуток = {np.dot(a, b)}')

a: [1 7 1 6 4]
b: [5 6 7 8 9]

скалярний добуток = 138


7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
mtx1 = np.random.randint(1, 10, (2, 2))
mtx2 = np.random.randint(1, 10, (2, 3))

print(f'mtx1:\n{mtx1}')
print()
print(f'mtx2:\n{mtx2}')
print()
print(f'Перемноження матриць:\n{np.dot(mtx1, mtx2)}')

mtx1:
[[5 7]
 [4 2]]

mtx2:
[[4 7 6]
 [8 4 2]]

Перемноження матриць:
[[76 63 44]
 [32 36 28]]


8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
mtx = np.random.randint(1, 10, (3, 3))

print(f'mtx:\n{mtx}')
print()
print(f'Обернена mtx:\n{np.linalg.inv(mtx)}')

mtx :
[[5 8 6]
 [5 9 5]
 [2 7 4]]

Обернена mtx :
[[ 0.03703704  0.37037037 -0.51851852]
 [-0.37037037  0.2962963   0.18518519]
 [ 0.62962963 -0.7037037   0.18518519]]


9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [132]:
mtx = np.random.random((4, 4))

print(f'mtx:\n{mtx}')
print()
print(f'Транспонтована mtx:\n{mtx.T}')

mtx:
[[0.83463248 0.63756189 0.51999813 0.7585856 ]
 [0.02375429 0.69879481 0.85068165 0.64986943]
 [0.98344986 0.43224439 0.82464578 0.45675433]
 [0.63158713 0.79744981 0.11134297 0.99760651]]

Транспонтована mtx:
[[0.83463248 0.02375429 0.98344986 0.63158713]
 [0.63756189 0.69879481 0.43224439 0.79744981]
 [0.51999813 0.85068165 0.82464578 0.11134297]
 [0.7585856  0.64986943 0.45675433 0.99760651]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
mtx = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, (4))

print(f'mtx:\n{mtx}')
print(f'vect:\n{vect}')
print()
print(f'Перемноження mtx * vect:\n{mtx * vect}')

mtx :
[[4 9 1 6]
 [7 1 9 9]
 [9 6 9 9]]
mtx :
[2 3 3 6]

Перемноження mtx * vect :
[[ 8 27  3 36]
 [14  3 27 54]
 [18 18 27 54]]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [133]:
mtx = np.random.random((3, 4))
vect = np.random.random((4))

print(f'mtx:\n{mtx}')
print(f'vect:\n{vect}')
print()
print(f'Перемноження mtx * vect:\n{mtx * vect}')

mtx:
[[0.49210244 0.98887322 0.13896894 0.36431997]
 [0.04082472 0.74733696 0.78208614 0.78534342]
 [0.11618321 0.56580518 0.78741417 0.48955448]]
vect:
[0.69698983 0.56993827 0.1895019  0.84244979]

Перемноження mtx * vect:
[[0.3429904  0.56359669 0.02633488 0.30692128]
 [0.02845442 0.42593593 0.14820681 0.6616124 ]
 [0.08097852 0.32247403 0.14921648 0.41242507]]


12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
mtx1 = np.random.randint(1, 10, (2, 2))
mtx2 = np.random.randint(1, 10, (2, 2))

print(f'mtx1:\n{mtx1}')
print(f'mtx2:\n{mtx2}')
print()
print(f'Перемноження mtx1 * mtx2:\n{mtx1 * mtx2}')

mtx :
[[7 5]
 [2 9]]
mtx :
[[7 3]
 [6 5]]

Перемноження mtx * vect :
[[49 15]
 [12 45]]


13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
mtx1 = np.random.randint(1, 10, (2, 2))
mtx2 = np.random.randint(1, 10, (2, 2))

print(f'mtx1:\n{mtx1}')
print(f'mtx2:\n{mtx2}')
print()
print(f'Добуток:\n{np.dot(mtx1, mtx2)}')

mtx1 :
[[3 9]
 [3 2]]
mtx2 :
[[7 6]
 [4 1]]

Добуток :
[[57 27]
 [29 20]]


14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
mtx = np.random.randint(1, 100, (5, 5))

print(f'mtx:\n{mtx}')
print()
print(f'Сума mtx:\n{np.sum(mtx)}')

mtx :
[[49 60 74 91 85]
 [43 57 20  4 82]
 [83 80 16 13 67]
 [22 25 38  7 61]
 [95 47 70 73 73]]

Сума mtx :
1335


15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
mtx1 = np.random.randint(1, 10, (4, 4))
mtx2 = np.random.randint(1, 10, (4, 4))

print(f'mtx1:\n{mtx1}')
print(f'mtx2:\n{mtx2}')
print()
print(f'Різниця:\n{np.subtract(mtx1, mtx2)}')

mtx1 :
[[5 2 6 5]
 [3 2 2 1]
 [1 4 4 6]
 [8 2 3 2]]
mtx2 :
[[6 4 6 3]
 [3 1 1 7]
 [5 7 8 7]
 [4 8 1 5]]

Різниця :
[[-1 -2  0  2]
 [ 0  1  1 -6]
 [-4 -3 -4 -1]
 [ 4 -6  2 -3]]


16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [131]:
mtx = np.random.random((3, 3))

print(f'mtx:\n{mtx}')
print()
print(f'mtx:\n{np.sum(mtx, axis=1)}')

mtx:
[[0.59560146 0.066064   0.98232357]
 [0.23228133 0.76142632 0.47439767]
 [0.51057205 0.44816616 0.03489115]]

mtx:
[1.64398903 1.46810533 0.99362936]


17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [120]:
mtx = np.random.randint(1, 100, (3, 4))

print(f'mtx:\n{mtx}')
print()
print(f'mtx_square:\n{np.square(mtx)}')


mtx :
[[20 88 41 37]
 [70 84 34 26]
 [21 52 37 66]]

mtx_square :
[[ 400 7744 1681 1369]
 [4900 7056 1156  676]
 [ 441 2704 1369 4356]]


18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [122]:
vect = np.random.randint(1, 50, (4))

print(f'vect:\n{vect}')
print()
print(f'vect sqrt:\n{np.sqrt(vect)}')


vect:
[33 13 13 36]

vect sqrt:
[5.74456265 3.60555128 3.60555128 6.        ]
