# **Елементи Лінійної Алгебри**

Основні поняття в лінійній алгебрі включають в себе вектори, матриці, лінійні перетворення, векторні простори, лінійні системи рівнянь, власні значення та вектори, діагоналізацію матриць та багато іншого.

### **Встановлення бібліотеки numpy**

In [1]:
# Install numpy using pip (usually not necessary in Google Colab, as numpy comes pre-installed) with the specific version 1.24.2
!pip install numpy==1.24.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 73.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.


In [1]:
# Reinstall numpy using pip with the latest version
!pip install numpy --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 46.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.2
    Uninstalling numpy-1.24.2:
      Successfully uninstalled numpy-1.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.25.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.25.0 which is incompatible.


In [2]:
# Import numpy as np
import numpy as np
np.__version__

'1.25.0'

In [3]:
!pip show numpy

Name: numpy
Version: 1.25.0
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, chex, cmdstanpy, contourpy, cufflinks, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, gensim, gym, h5py, holoviews, hyperopt, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn-pandas, soxr, spacy, statsmodels, tables, ten

## **Вектори**

Будь-яку точку нашої координатної площини можна представити у вигляді вектора, який будемо записувати у вигляді стовця **v** = \begin{bmatrix} x \\ y \\ \end{bmatrix}



Тобто, **вектор-стовпець** можемо представити таким чином:
**x** = \begin{bmatrix} 4 \\ 5 \\ 2 \\ 4 \\ 6 \\ \end{bmatrix}

де **x** - це вектор, що містить 5 елементів 4, 5, 2, 4, 6 і належить лінійному простору R<sup>5</sup>.





А **вектор-рядок** часто позначають так:
**x** = \begin{bmatrix} 4 \ 5 \ 2 \ 4 \ 6 \ \end{bmatrix}
де **x** — це вектор-рядок, що також містить п'ять елементів 4, 5, 2, 4, 6,проте належить лінійному простору R<sup>1x5</sup>

**Основні операції, котрі ми можемо робити з векторами**:

* додавання/віднімання скаляра та вектора
* множити вектор на скаляр (число)
* додавати два вектори
* віднімати два вектори
* шукати скалярний добуток двох векторів

### **Створення масивів та матриць в `numpy`**

In [ ]:
help(np.array)

In [6]:
# create a np.array vector with 5 elements from 1 to 5 with dtype=float
a = np.array(object=[1,2,3,4,5], dtype=float)

# print the vector
print(a)

a

[1. 2. 3. 4. 5.]


array([1., 2., 3., 4., 5.])

### **Додавання/віднімання скаляра та вектора**

In [7]:
# create a np.array vector with 5 elements from 1 to 5 with dtype=float
a = np.array(object=[1,2,3,4,5], dtype=float)

# print the vector
print(a)


[1. 2. 3. 4. 5.]


In [14]:
# add a constant to a vector and print it
print(a + 1)

# subtract a constant from a vector and print it
print(a - 1)

# do the same but with constant vectors
print(a + np.array([1,1,1,1,1]))
print(a - np.array([1,1,1,1,1]))



[2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4.]
[2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4.]


### **Множення на скаляр**

Коли ми множимо вектор на скаляр, то отримуємо вектор, який належить цьому ж лінійному простору R<sup>a</sup>, що й початковий вектор.

$$\lambda \cdot \mathbf{a} \in \mathbb{R}$$

  
А результатом буде те, що кожен елемент вектора, тобто координати, будуть помножені на число $$\lambda$$

In [15]:
# create a np.array vector with 5 elements from 1 to 5 with dtype=float
a = np.array(object=[1,2,3,4,5], dtype=float)

# print the vector
print(a)


[1. 2. 3. 4. 5.]


In [17]:
# Multiply the vector a by a scalar and assign the result to b
b = a * 10

# print the vector b
print(b)


[10. 20. 30. 40. 50.]


### **Додавання та віднімання двох векторів**

In [23]:
# create a np.array vector with 5 elements from 1 to 5 with dtype=float
a = np.array([1,2,3,4,5])

# create a np.array vector with 5 elements from 1 to 5 with dtype=float
b = np.array([1,2,3,4,5])

# print the size of the vector a, and b
print(a.size)
print(b.size)


5
5


In [24]:
# add vectors a and b, and print it out
print(a + b)

# subtract the vector b from the vector a, and print it out
print(a - b)


[ 2  4  6  8 10]
[0 0 0 0 0]


### **Скалярний добуток, по-елементне множення та ділення векторів**

Скалярним добутком двох векторів буде сума попарно перемножених відповідних координат цих двох векторів. Для прикладу обчислимо скалярний добуток двох тривимірних векторів **x** і **y** у явному вигляді. Так, часом вектори позначають в літературі просто як жирні друковані літери, і таке позначення зустрічається на рівні зі стрілочкою:

**x** · **y** = x₁y₁ + x₂y₂ + x₃y₃

У цьому виразі **x** і **y** - вектори, а x₁, x₂, x₃ і y₁, y₂, y₃ - їх відповідні координати. Крапка позначає скалярний добуток.


In [36]:
# create a np.array vector with 5 elements from 1 to 5 with dtype=float
a = np.array([1,2,3,4,5])

# create a np.array vector with 5 elements from 1 to 5 with dtype=float
b = np.array([-1,-2,-3,-4,-5])


In [40]:
print(a)
print(b)
c = a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3] + a[4] * b[4]
c

[1 2 3 4 5]
[-1 -2 -3 -4 -5]


-55

In [39]:
# multiply the vector a by the vector b and print it out
c = a * b
print(c)

[ -1  -4  -9 -16 -25]


In [42]:
# calculate a dot product and assign the result to the vector c
c = np.dot(a, b)

# use a magic function
d = a@b

# print the result
print(c)
print(d)


-55
-55


In [44]:
# divide the vector a by the vector b, and assign the result to the vector c
c = a / b

# print the result
print(c)


[-1. -1. -1. -1. -1.]


### **Базис векторів**

У лінійній алгебрі базис векторів — це набір векторів, що використовуються для опису інших векторів у лінійному просторі. Кожен вектор в просторі можна представити унікальною лінійною комбінацією базисних векторів з деякими коефіцієнтами.

Наприклад, в двовимірному просторі, вектори (1,0) та (0,1) можуть служити базисом. Будь-який інший вектор у цьому просторі можна представити як лінійну комбінацію цих базисних векторів зі своїми власними коефіцієнтами. Наприклад, вектор (3,4) можна представити як 3∗(1,0)+4∗(0,1).


## **Матриці**

Матрицею розмірності m×n називатиметься сукупність чисел, які будуть розміщені у таблиці з **m рядочків** та **n стовпчиків**:

\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{bmatrix}

Числа **a<sub>ij</sub> називаються елементами матриці**. Таким чином, перший індекс **i** елементу відповідає за **номер рядка**, у якому розміщений даний елемент, а другий індекс **j — номер стовця**.

Така матриця буде належати лінійному простору **R<sup>m×n</sup>**.


In [55]:
# Create a numpy matrix with a specific data type = int
A = np.array([[1, 2],[1,2]], dtype=bool)

# Display the result
print(A)


[[ True  True]
 [ True  True]]


### **Розмірність матриці**

In [69]:
# Check the dimensions of the matrix, and print it out
print(A.shape)

# Check the dimension of the vector, and print it out
print(a.shape)


(2, 2)
(3,)


### **Усі атрибути масиву ndarray для інспекції зведені в таблиці**

Атрибут | Опис
--- | ---
`shape` | Розміри масиву: розмір масиву вздовж кожної з його осей, повертається як кортеж цілих чисел
`ndim` | Кількість осей (вимірів). Зверніть увагу: `ndim` == `len(shape)`
`size` | Загальна кількість елементів у масиві, рівна добутку елементів кортежу `shape`
`dtype` | Тип даних масиву (див. нижче)
`data` | «Буфер» у пам'яті, що містить дійсні елементи масиву
`itemsize` | Розмір у байтах кожного елемента

In [70]:
print(f"shape: {A.shape}")
print(f"ndim: {A.ndim}")
print(f"size: {A.size}")
print(f"dtype: {A.dtype}")
print(f"itemsize: {A.itemsize}")

shape: (2, 2)
ndim: 2
size: 4
dtype: bool
itemsize: 1


### **По-елементне множення матриць**

In [74]:
# Create a matrix A
A = np.array([[1,2], [1,2]], dtype=float)
print(A)

# Create a matrix B
B = np.array([[-1, -2], [-1, -2]], dtype=float)
print(B)

# Multiply the matrix A and B, and assign the result to C
C = A * B

# print the matrix C
print(C)


[[1. 2.]
 [1. 2.]]
[[-1. -2.]
 [-1. -2.]]
[[-1. -4.]
 [-1. -4.]]


### **Матричний добуток**

Якщо у нас є дві матриці A та B, де **A<sub>m×n</sub>** (тобто має **m рядків і n стовпців**), а **B<sub>n×p</sub>** (має **n рядків і p стовпців**), то їх добуток **A*B буде матрицею C<sub>m×p</sub>**, де кожен елемент нової матриці **c<sub>ij</sub> обчислюється як скалярний добуток** i-ого рядка матриці A, тобто **a<sub>i</sub>**, та j-ого стовпця матриці B - **b<sub>j</sub>**.

**Математичну формулу можна записати так:**

A = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}
B = \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix}

**Множення матриць А та В можно представити таким чином:**

A*B = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}
*
\begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix}
=
\begin{bmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{bmatrix}


In [89]:
print(A * B)
print(np.multiply(A, B))

print(np.dot(A, B))


[[1 4 9]
 [1 4 9]
 [1 4 9]]
[[1 4 9]
 [1 4 9]
 [1 4 9]]
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [86]:
# create a matrix A(2x3)
A = np.array([[1,2,3],[1,2,3],[1,2,3]])

# create a matrix B(3x1)
B = np.array([[1, 2, 3],[1,2,3],[1,2,3]])
print(A)
print(B)

# calculate a matrix multiplication, and assign the result to C
C = np.dot(A, B)

# print the matrix C
print(C)

# use a magic function
D = A@B

# print the matrix D
print(D)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


### **Транспонування та зміна форми матриць в numpy**

A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}

Транспонована матриця А<sup>T</sup>:

A<sup>T</sup> = \begin{bmatrix} a_{11} & a_{21} & a_{31} \\ a_{12} & a_{22} & a_{32} \\ a_{13} & a_{23} & a_{33} \end{bmatrix}


In [93]:
# Create a matrix A(3x3)
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

# print the matrix A
print(A)

# transpose the matrix A, and assign the result to B
B = A.T

# print the result
print(B)

C = np.transpose(A)
print(C)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Reshaping the matrix

In [102]:
# Create a matrix A(3x4)
A = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(A)

# Reshape the matrix to A(4x3)
print(A.reshape(4, 3))
print(A.reshape(6, 2))
print(A.reshape(2, 6))

# Flatten the matrix
print(A.flatten())



[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3]
 [4 1 2]
 [3 4 1]
 [2 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 3 4 1 2]
 [3 4 1 2 3 4]]
[1 2 3 4 1 2 3 4 1 2 3 4]


### **Одинична матриця**

I = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}

A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}

Множення на одиничну матрицю не змінює матрицю:
$$A \cdot I = I \cdot A = A$$



In [112]:
# Create an identity matrix I
I = np.eye(3, k=0)
I = np.identity(3)
print(I)

# Create a matrix A
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

# multiply I by A, and A by I, and assign the results to C and D
C = np.dot(A, I)
D = np.dot(I, A)

# print C and D
print(C)
print(D)
print(C==A)
print(C==D)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### **Обернена матриця**

Обернена матриця - це спеціальний тип квадратної матриці, для якої добуток з вихідною матрицею (в будь-якому порядку) дає одиничну матрицю.

Якщо матриця A має обернену матрицю, то її позначають як A<sup>-1</sup>, і вона володіє властивістю:

$$ A \cdot A^{-1} = A^{-1} \cdot A = I $$

де I - це одинична матриця.


In [115]:
# Create a matrix A
A = np.array([[1,2,3], [4,5,6], [7,8,10]])

# Create an inverse matrix of A
A_inv = np.linalg.inv(A)

# print the inverse matrix
print(A_inv)
print(np.linalg.inv(A_inv))


[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]


### **Властивості операцій з матрицями**

\begin{align*}
A + B & = B + A & \text{(Комутативність додавання)} \\
A + (B + C) & = (A + B) + C & \text{(Асоціативність додавання)} \\
A \cdot (B \cdot C) & = (A \cdot B) \cdot C & \text{(Асоціативність множення)} \\
A \cdot (B + C) & = A \cdot B + A \cdot C & \text{(Дистрибутивність)} \\
(A + B)^T & = A^T + B^T & \text{(Транспонування суми)} \\
(AB)^T & = B^T A^T & \text{(Транспонування добутку)} \\
(A^T)^T & = A & \text{(Двічі транспонована матриця)} \\
(A^{-1})^{-1} & = A & \text{(Обернена до оберненої матриці)} \\
(AB)^{-1} & = B^{-1} A^{-1} & \text{(Обернена до добутку матриць)} \\
I^{-1} & = I & \text{(Обернена до одиничної матриці)}
\end{align*}
